# Generated by Django 5.1.6 on 2026-03-01 15:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='lobby', max_length=32)),
                ('turn_seat_index', models.PositiveSmallIntegerField(default=0)),
                ('state_version', models.PositiveIntegerField(default=0)),
                ('last_dice_1', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('last_dice_2', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('last_roll_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_index', models.PositiveSmallIntegerField()),
                ('money', models.IntegerField(default=1500)),
                ('position_index', models.PositiveSmallIntegerField(default=0)),
                ('in_jail', models.BooleanField(default=False)),
                ('jail_turns_left', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='game.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('game', 'seat_index'), name='uniq_game_seat'), models.UniqueConstraint(fields=('game', 'user'), name='uniq_game_user')],
            },
        ),
    ]
