# Generated by Django 5.1.6 on 2026-03-05 21:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="playerstate",
            name="pending_buy_tile_index",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="PropertyState",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("tile_index", models.PositiveSmallIntegerField()),
                ("owner_seat_index", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("purchase_price", models.PositiveIntegerField(default=100)),
                ("base_rent", models.PositiveIntegerField(default=10)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="properties",
                        to="game.game",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(fields=("game", "tile_index"), name="uniq_game_tile"),
                ],
            },
        ),
    ]
