# Generated by Django 5.1.6 on 2026-03-08 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_playerstate_pending_buy_propertystate'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerstate',
            name='pending_event_kind',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='playerstate',
            name='pending_event_tile_index',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
