# Generated by Cascade on 2026-03-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0003_playerstate_pending_event_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="chance_deck",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="game",
            name="community_chest_deck",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="playerstate",
            name="chance_jail_free_cards",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="playerstate",
            name="community_chest_jail_free_cards",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="playerstate",
            name="pending_event_card_id",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
