# Generated by Cascade on 2026-03-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0004_game_decks_player_event_cards"),
    ]

    operations = [
        migrations.AddField(
            model_name="playerstate",
            name="connection_count",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
